version: "3.9"

services:
  frontend:
    image: classactivityweb:v2
    container_name: frontend
    ports:
      - "9002:80"

  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=dummydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
